version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  cache:
    image: redis:latest

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/templates:/directus/templates
    depends_on:
      - cache
      - db
    environment:
      SECRET: ${SECRET_PHRASE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED} 
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE} 
      CACHE_STORE: ${CACHE_STORE}
      REDIS: ${REDIS_URL}

      MAX_RELATIONAL_DEPTH: 100
      
      USER_REGISTER_URL_ALLOW_LIST: ${USER_REGISTER_URL_ALLOW_LIST}
      PASSWORD_RESET_URL_ALLOW_LIST: ${PASSWORD_RESET_URL_ALLOW_LIST}

      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}

      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}

  nginx:
    image: nginx:latest
    depends_on:
      - directus
    ports:
      - "80:80" # Expose NGINX to the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    restart: always
